services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "808:80"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp_db
      MYSQL_USER: c
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: 