services:
  jupyter:
    image: jupyter/base-notebook:latest
    container_name: jupyter_local
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=mysecret
      - TZ=Europe/Moscow
    networks:
      - jupyter-net

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp_db
      MYSQL_USER: myapp_user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - jupyter-net

volumes:
  db_data:     
networks:
  jupyter-net:
    driver: bridge